### ISSUE TITLE
Graphsync does not return an error when the request context is cancelled

### ISSUE THREAD

**Issue by dirkmc** [ipfs/go-graphsync#142]
We found a problem in go-data-transfer whereby when the node shuts down
- the context for all the outstanding requests are cancelled
- go-data-transfer's graphsync transport consumes all outstanding requests
- the graphsync request completes without returning an error
- the transfer is marked as complete, even though it is incomplete

We worked around this problem by checking the if the request context was closed when the request finishes: https://github.com/filecoin-project/go-data-transfer/pull/134. The correct solution would be to fix the underlying problem, which appears to be that graphsync does not return an error when the request context is cancelled.

**Comment by hannahhoward** [comment]
This is no longer true I think
