### ISSUE TITLE
Configurable graphsync response limit

### ISSUE THREAD

**Issue by dirkmc** [ipfs/go-graphsync#162]
#### Background

Currently graphsync has a hardcoded limit in the number of responses it will process concurrently to mitigate against DoS.
However with the recent improvements to memory usage, it should be safe to raise this limit. Context: https://github.com/filecoin-project/lotus/issues/5752#issuecomment-805631235

#### Proposal

Make the response limit configurable

**Comment by aarshkshah1992** [comment]
@dirkmc This is already configurable in Graphsync. Please see `MaxInProgressRequests `.
