### ISSUE TITLE
RFC: Graphsync External Interfaces for FileCoin

### ISSUE THREAD

**Issue by hannahhoward** [ipfs/go-graphsync#18]
This document is meant to stimulate discussion and work towards a final proposal for the external interfaces that GraphSync provides that FileCoin will use.

## Go-IPLD-Prime

`go-graphsync` relies on `go-ipld-prime` to traverse IPLD Selectors in an IPLD graph. `go-ipld-prime` is a complete rewrite of go IPLD libraries, and looks A LOT different than `go-ipld-format` and `go-ipld-cbor`. In order to use `go-graphsync`, some understanding and use of `go-ipld-prime` concepts is necessary. However, go-graphsync can provide some translation layers as necessary if FileCoin does not want to integrate `go-ipld-prime` in the rest of its code base

## Initializing a GraphSync Exchange

Here is the current proposed signature for initializing GraphSync:

```golang
func New(ctx context.Context, 
        host libp2p.Host, 
        loader ipld.Loader)
```

Parameter Notes:

1. `context` is just the parent context for all of GraphSync
2. `host` is any libp2p host
2. `loader` is used to load blocks from the local block store when RESPONDING to requests from other clients. See the IPLD loader interface: https://github.com/ipld/go-ipld-prime/blob/master/linking.go

### How To Write A Loader From The Stuff You Know

Coming from a pre-`go-ipld-prime` world, you probably expect a link loading function signature to look like this:

```
type Cid2BlockFn func (lnk cid.Cid) (blocks.Block, error)
```

in `go-ipld-prime`, the signature for a link loader is as follows:

```
type Loader func(lnk Link, lnkCtx LinkContext) (io.Reader, error)
```

`go-ipld-prime` intentionally keeps its interfaces as abstract as possible to limit dependencies on other ipfs/filecoin specific packages. An IPLD Link is an abstraction for a CID, and IPLD expects io.Reader's rather than an actual block. IPLD provides a `cidLink` package for working with Links that use CIDs as the underlying data, and it's safe to assume that's the type in use if your code deals only with CIDs. Anyway, a conversion would look something like this:

```golang
import (
   ipld "github.com/ipld/go-ipld-prime"
   cidLink "github.com/ipld/go-ipld-prime/linking/cid"
)

func LoaderFromCid2BlockFn(cid2BlockFn Cid2BlockFn) ipld.Loader {
	return func(lnk ipld.Link, lnkCtx ipld.LinkContext) (io.Reader, error) {
		asCidLink, ok := lnk.(cidlink.Link)
		if !ok {
			return nil, fmt.Errorf("Unsupported Link Type")
		}
		block, err := cid2BlockFn(asCidLink.Cid)
		if err != nil {
			return nil, err
		}
		return bytes.NewReader(block.RawData()), nil
	}
}
```

Go GraphSync can provide the above as a utility function if neccesary.

## Calling Graphsync

```golang
graphSync.Request(ctx context.Context, p peer.ID, cidRootedSelector Node) (<-chan ResponseProgress, <-chan error)
```

Paramater Notes:
1. `ctx` is the context for this request. To cancel an in progress request, cancel the context.
2. `p` is the peer you will send this request to
3. `cidRootedSelector` is the a go-ipld-prime node

### Building a path selector

A rooted selector is a `go-ipld-prime` node that follows the spec outlined here: https://github.com/ipld/specs/pull/95

`go-ipld-prime` provides a series of builder interfaces for building this kind of structured data into a node. Assuming, in Filecoin's case, you are beginning with a CID and a path, represented by an array of strings, you could construct the node as follows:

```golang
import (
	ipld "github.com/ipld/go-ipld-prime"
	free "github.com/ipld/go-ipld-prime/impl/free"
	fluent "github.com/ipld/go-ipld-prime/fluent"
        cidLink "github.com/ipld/go-ipld-prime/linking/cid"
)

func SelectorSpecFromCidAndPath(lnk cid.Cid, pathSegments []string) (ipld.Node, error) {
	var node ipld.Node
	err := fluent.Recover(func() {
		builder := fluent.WrapNodeBuilder(free.NodeBuilder())
		node = builder.CreateMap(func (mb fluent.MapBuilder, knb fluent.NodeBuilder, vnb fluent.NodeBuilder) {
			mb.Insert(knb.CreateString("root"), vnb.CreateLink(cidLink.Link{lnk}))
			mb.Insert(knb.CreateString("selectors"), 
			vnb.CreateList(func (lb fluent.ListBuilder, vnb fluent.NodeBuilder) {
				for _, pathSegment := range pathSegments {
					lb.Append(CreateMap(
						func (mb fluent.MapBuilder, knb fluent.NodeBuilder, vnb fluent.NodeBuilder) {
							mb.Insert(knb.CreateString("selectPath"), vnb.CreateString(pathSegment))
						},
					))
				}
			}))
		});
	})
	if err != nil {
		return nil, err
	}
	return node, nil
}
```

go-graphsync can provide this as a utility function

### Response Type

Outstanding Question 1: Nodes or Blocks?

Does GraphSync return go-ipld-prime nodes, or blocks? This is a tough question. The advantage of nodes is that they are way more informative and represent structured data. They are also the data type that go-ipld-prime's selectors work with. At the same time, returning Nodes means that the GraphSync client really needs to understand go-ipld-prime and integrate with it. Right now, neither Filecoin or go-ipfs integrate with go-ipld-prime.

The other integrations points are:
1. The initialization parameters which may not be neccesary to begin with (see above), and are otherwise easy to assemble from the go-ipld-prime library
1. Building selectorSpecs -- this seems unavoidable, but is also a novel use case that does not necessarily require changing a lot of code to use go-ipld-prime elsewhere in the client library

By contrast if a selection returns Nodes, the Graphsync client really needs to understand them -- particularly cause nodes are not necessarily a whole block, but can exist inside a block.

**Comment by warpfork** [comment]
re: multicodecs: I think I've finally plotted a new way through the multicodec/linking area that looks good and clean, so I'm going through that like a hot knife through butter this weekend, and hopefully it'll be clearer how to use it on monday or so.

re: slightly different loader interfaces: I didn't exactly follow on where the divergence is, but fwiw, yes, it's intentional that go-ipld-prime signatures do *not* use the block interfaces.  Two reasons: it's desirable that IPLD stand on its own as much as possible, and we *can* do it without explicit block types, therefore we *should*;  and also I have a slight grudge against most of the current block APIs as they're antithetical to streaming operation, hence all the streaming readers and writers in the go-ipld-prime interfaces.  I'm sorry if that adds some glue code to your side, but I'd rather do that and eventually carry the war for streaming interfaces towards the block side instead of backsliding :see_no_evil:

re: nodes or blocks: I'd go for blocks in the graphsync wire stuff.  We can parse them back into nodes on the receiver side, and that should be a clean enough boundary.

**Comment by hannahhoward** [comment]
@warpfork -- yea to be clear -- re: blocks vs node -- the question is whether to parse them back to nodes before filecoin gets them :)

**Comment by warpfork** [comment]
ah, yeah.  That's... an interesting question.

It might come down to some conversation with the filecoin folks about what our integration (/migration) plans might be there.  E.g., Nodes might be better long run; but if we have a long lived migration strategy where they don't start using the new Nodes everywhere right away, then blocks will be safer.
