### ISSUE TITLE
Refactor: Use TaskQueue in ResponseManager

### ISSUE THREAD

**Issue by hannahhoward** [ipfs/go-graphsync#232]
# What

We can simplify the ResponseManager by refactoring it to use the extracted TaskQueue logic. Even better if we can successfully extract the queryExecutor to its own module and unit test it (not as essential though), and then move instantiation of the query executor up to the top level module.

**Comment by davidd8** [comment]
Assigning to @rvagg as a good starter task for graphsync.

**Comment by rvagg** [comment]
Working on this, but getting my head around what's going on in here and what needs to be replaced is requiring some learning investment.
