### ISSUE TITLE
Get rid of RunTraversal, merge with query executor

### ISSUE THREAD

**Issue by hannahhoward** [ipfs/go-graphsync#264]
once https://github.com/ipfs/go-graphsync/issues/232 is done, I think it's time to examine whether we can move RunTraversal into the query executor.

I started a hack on this -- https://github.com/ipfs/go-graphsync/pull/263

Maybe someone can finish it off (will require a lot of test rejiggering 👎 )

**Comment by rvagg** [comment]
all completed in #244's merge
