### ISSUE TITLE
Discussion: Add an imperative "SendExtensions" Call to GraphSync top level interface

### ISSUE THREAD

**Issue by hannahhoward** [ipfs/go-graphsync#348]
In order to get all data transfer libp2p messages into the protocol, we should add an imperative "SendExtensions" call to the top level interface.

This call would:
- if the RequestID matches an in progress request --> send request with type Update with the extensions
- if the RequestID matches an in progress response -> send response with code PartialResponse with extensions

**Comment by rvagg** [comment]
This would just be sugar, right? A fairly straightforward message construction internally that lets the caller skip all the messy bits and just provide requestid and extension data?

**Comment by hannahhoward** [comment]
Yes with the caveat that it checks against in progress requests and responses to figure out whether to send a request or response.

**Comment by hannahhoward** [comment]
I also wonder if this should just be called "SendUpdate"
