### ISSUE TITLE
Backwards compatibility for ipldbridge

### ISSUE THREAD

**Issue by jsonsivar** [ipfs/go-graphsync#82]
Hello - so our project Space (https://github.com/fleekhq/space-daemon) is using both `github.com/textileio/textile` and `go-ipfs`.  Textile brings in some Filecoin dependencies so there is now a conflict in the expected version of `go-graphsync` between Filecoin and `go-ipfs`.

The problem is that since `ipldbridge` was removed after `v0.0.5` in this repo, `go-ipfs` `v0.6.0` still depends on that. Meanwhile the Filecoin dependencies listed here need a newer version of `go-graphsync`:
```
463:github.com/filecoin-project/go-fil-markets@v0.3.0 github.com/ipfs/go-graphsync@v0.0.6-0.20200504202014-9d5f2c26a103
537:github.com/filecoin-project/lotus@v0.4.0 github.com/ipfs/go-graphsync@v0.0.6-0.20200504202014-9d5f2c26a103
671:github.com/filecoin-project/go-data-transfer@v0.3.0 github.com/ipfs/go-graphsync@v0.0.6-0.20200504202014-9d5f2c26a103
```

Are there plans to make this compatible with both Filecoin and IPFS? Apologies if this isn't the best place to post this, maybe it should be done on the Filecoin side but thought I'd start here and get some input before proceeding.  Thanks in advance!

**Comment by ribasushi** [comment]
@aschmahmann I will look into this today, response should come in by EOD eastern

**Comment by ribasushi** [comment]
@jsonsivar branch https://github.com/ipfs/go-ipfs/tree/chore/bump-graphsync-dep should take care of your problem. Please test it when time permits and report back. Apologies for the delays!

**Comment by jsonsivar** [comment]
> @jsonsivar branch https://github.com/ipfs/go-ipfs/tree/chore/bump-graphsync-dep should take care of your problem. Please test it when time permits and report back. Apologies for the delays!

Thank you for this @ribasushi. Will give it a shot and confirm here. cc @maurycy

**Comment by jsonsivar** [comment]
@ribasushi Just tested this out and it fixed it :+1: Thanks again.  Not sure if we need to wait for it to get merged before closing this but will let you close it as you see fit.  Is it safe to assume this fix will be in the next release of `go-ipfs`?

**Comment by hannahhoward** [comment]
thanks @ribasushi yep the solution is for sure to upgrade graphsync in IPFS

**Comment by ribasushi** [comment]
This is merged/in RC
Closing
